# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bfdb7239e387f78662c1851c94f3aa8c79a27af4c2185d36061953c1d38f9f8c2ef75e3c387786b53732cfe6e9f4d7096d76e0ba507b26f61950c8d59a8e688

test:
  secret_key_base: 456e0b5fc16bfdcb68c13a31145afccb3b5db85897ee3839115f937d35003bbb99300a84a30ee62c9f0cbc424506450e319064ec776224e47daee9818b1e289f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
